version: "1"
rules:                          # Array of rules
  - base: frq-nixos-19.09       # Required. Target branch
    upstream: NixOS:nixos-19.09 # Required. Must be in the same fork network.
    mergeMethod: rebase         # Optional, one of [none, merge, squash, rebase, hardreset], Default: none.
